### ISSUE TITLE
Improper parsing of multiline arrays

### ISSUE THREAD

**Issue by Zert** [zamith/tomlex#8]
When newline breaks the array in config, Tomlex returns wrong value of a parameter:

```
iex(1)> "a = [\"s1\", \"s2\"] " |> Tomlex.load
%{a: ["s1", "s2"]}
iex(2)> "a = [\n\"s1\", \"s2\"] " |> Tomlex.load
%{a: "["}
```

**Comment by zamith** [comment]
I'm sorry about the delay. Unfortunately I haven't had the time I'd like to dedicate to this. Have you had any luck in fixing the issue?

**Comment by Weatherproof** [comment]
I'm also having this problem. I even tested this against the [TOML Github Docs](https://github.com/toml-lang/toml) and it didn't produce the expected result :(

```
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

Should parse to
```
{
  "fruit": [
    {
      "name": "apple",
      "physical": {
        "color": "red",
        "shape": "round"
      },
      "variety": [
        { "name": "red delicious" },
        { "name": "granny smith" }
      ]
    },
    {
      "name": "banana",
      "variety": [
        { "name": "plantain" }
      ]
    }
  ]
}
```

Instead it returns an error:
```
iex(1)> test = File.read!("fruit.toml") |> Tomlex.load
** (FunctionClauseError) no function clause matching in Keyword.get_and_update/4
    (elixir) lib/keyword.ex:227: Keyword.get_and_update([%{name: "apple"}], [], :physical, #Function<12.57371001/1 in Kernel.put_in/3>)
    (elixir) lib/map.ex:694: Map.get_and_update/3
    (elixir) lib/kernel.ex:1831: Kernel.put_in/3
             lib/tomlex/parser.ex:85: Tomlex.Parser.build_nested_table/4
             lib/tomlex/parser.ex:36: Tomlex.Parser.parse/2
```

**Comment by zamith** [comment]
@Weatherproof That's actually an Array of Tables, which is not supported yet as you can see on the roadmap, not the same issue I think.

I'll try to work on both of these issues, but as I mentioned above I haven't had that much time.

**Comment by Weatherproof** [comment]
Ah, I missed the roadmap. No worries, I'll just use json :-)
